numpy funciones matematicas
pandas
matplotlib

In [1]:
pip install numpy

Funciones de Numpy argmax()-argmin()/Max-min en Python
sqrt() Para sacar la raiz cuadrada

In [4]:
import numpy as np

In [2]:
print ("Hola")

Hola


In [3]:
import sys

#### Creando una lista

In [5]:
lista = list(range(1,11))
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

Pasando de lista a un Array (array es una funcion de numpy)

In [6]:
arreglo = np.array(lista)
arreglo

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

#### Crear una lista de solo numeros unos

In [7]:
unos = np.ones(24)
unos

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1.])

In [8]:
ceros = np.zeros(100)
ceros

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [9]:
type(ceros)

numpy.ndarray

In [10]:
arreglo.dtype

dtype('int64')

In [12]:
lista2 = ["vale", 22, True]
lista2

['vale', 22, True]

In [13]:
arreglo2 = np.array(lista2)
arreglo2

array(['vale', '22', 'True'], dtype='<U21')

### Consultando la cantidad de memoria ocupada

In [14]:
memoria_lista = sys.getsizeof(lista)
memoria_arreglo = arreglo.nbytes

print(f"Memoria ocupada por la lista: {memoria_lista} bytes")
print(f"Memorua ocupada por el array: {memoria_arreglo} bytes")

Memoria ocupada por la lista: 136 bytes
Memorua ocupada por el array: 80 bytes


### Promedio del arreglo

In [15]:
promedio = np.mean(lista)
promedio

np.float64(5.5)

In [16]:
new_arreglo = arreglo.astype(np.float64)
new_arreglo

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

### Aplicando el paquete random

Se genera una lista de numeros enteros aleatorios, que van desde el numero que le deseamos escoger

In [17]:
np.random.randint(10)

1

In [18]:
np.random.randint(1,100)

16

In [19]:
np.random.rand(1,10,4)

array([[[0.35268588, 0.32037515, 0.43720499, 0.94012738],
        [0.89076334, 0.5097604 , 0.9188359 , 0.19015481],
        [0.22617551, 0.42099961, 0.17604814, 0.64093766],
        [0.56657933, 0.05788422, 0.43221631, 0.68279078],
        [0.50245175, 0.33046599, 0.05096789, 0.35997872],
        [0.46557293, 0.15647033, 0.13948077, 0.36487021],
        [0.07397333, 0.02884558, 0.81504058, 0.63485902],
        [0.5474572 , 0.42173489, 0.21386917, 0.32466617],
        [0.56582598, 0.28213009, 0.3290065 , 0.34383587],
        [0.05258666, 0.92942762, 0.82306898, 0.09044801]]])